### ISSUE TITLE
relation-delete leads to MDB_PAGE_FULL in lmdb 0.9.23

### ISSUE THREAD

**Issue by sph-mn** [sph-mn/sph-db#1]
* when trying to delete at least 5041 relations
* occurs since lmdb commit [1ffe472a080fcd3c7dab6e352848703ad7adbe14](https://github.com/LMDB/lmdb/commit/1ffe472a080fcd3c7dab6e352848703ad7adbe14), first included in release 0.9.23 from 2018-12-19
* goes away if MDB_WRITEMAP is disabled (currently enabled by default -> default is going to be changed)

**Comment by jkalbhenn** [comment]
default has been changed. exact cause might still have to be investigated.

**Comment by sph-mn** [comment]
default has been changed. exact cause might still have to be investigated.
